### ISSUE TITLE
Api Level 3

### ISSUE THREAD

**Issue by lmcintyre** [ff-meli/OrchestrionPlugin#18]
Just letting you know, Dalamud API level 3 is coming out soon (for patch 5.5, April 13th), and plugins will need a recompile.

**Comment by ff-meli** [comment]
Ah thanks for the heads up.

Since I obviously haven't had the time I was hoping for to work on this, I'll probably just _actually_ merge your old PR into master for now, so that the songlist at least will stay up to date (assuming yours is still maintained).  Sorry for kind of dropping the ball on all of that, life hasn't been cooperating x.x

**Comment by ff-meli** [comment]
API level updated in 58d4c5d ... other stuff still coming (yes I'm slow :( )
